### ISSUE TITLE
Testissue2

### ISSUE THREAD

**Issue by jrudolph** [jrudolph/jrudolph.github.com#2]

**Comment by jrudolph** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed):
https://jenkins.akka.io/job/pr-validator-per-commit-jenkins/3267/

**Comment by jrudolph** [comment]
Error lines in https://jenkins.akka.io/job/pr-validator-per-commit-jenkins/3268/:

```
  9950 Test akka.stream.javadsl.FlowTest.mustBeAbleToRecover failed: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1, took 3.046 sec
  9951     at scala.Predef$.assert(Predef.scala:179)
  9952     at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
  9953     at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
  9954     at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
  9955     at akka.testkit.JavaTestKit.expectMsgEquals(JavaTestKit.java:378)
  9956     at akka.stream.javadsl.FlowTest.mustBeAbleToRecover(FlowTest.java:548)
  9957     ...
 10693 Failed: Total 867, Failed 2, Errors 0, Passed 865, Pending 22
 10694 Failed tests:
 10695 	akka.stream.scaladsl.SinkForeachParallelSpec
 10696 	akka.stream.javadsl.FlowTest
 14047 (akka-stream-tests-experimental/test:test) sbt.TestsFailedException: Tests unsuccessful
 14048 Total time: 925 s, completed Jul 21, 2015 6:38:55 PM
```

**Comment by jrudolph** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed):
https://jenkins.akka.io/job/pr-validator-per-commit-jenkins/3269/

**Comment by jrudolph** [comment]
Error lines in https://jenkins.akka.io/job/pr-validator-per-commit-jenkins/3268/:

```
  9950 Test akka.stream.javadsl.FlowTest.mustBeAbleToRecover failed: java.lang.AssertionError: assertion failed: timeout (3 seconds) during expectMsg while waiting for 1, took 3.046 sec
  9951     at scala.Predef$.assert(Predef.scala:179)
  9952     at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:338)
  9953     at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:315)
  9954     at akka.testkit.TestKit.expectMsg(TestKit.scala:718)
  9955     at akka.testkit.JavaTestKit.expectMsgEquals(JavaTestKit.java:378)
  9956     at akka.stream.javadsl.FlowTest.mustBeAbleToRecover(FlowTest.java:548)
  9957     ...
 10693 Failed: Total 867, Failed 2, Errors 0, Passed 865, Pending 22
 10694 Failed tests:
 10695 	akka.stream.scaladsl.SinkForeachParallelSpec
 10696 	akka.stream.javadsl.FlowTest
 14047 (akka-stream-tests-experimental/test:test) sbt.TestsFailedException: Tests unsuccessful
 14048 Total time: 925 s, completed Jul 21, 2015 6:38:55 PM
```
